### ISSUE TITLE
thread '<unnamed>' panicked at 'HirDisplay failed when calling Display::fmt!', /home/bjorn/.cargo/registry/src/github.com-1ecc6299db9ec823/ra_ap_hir_ty-0.0.30/src/display.rs:222:17

### ISSUE THREAD

**Issue by bjorn3** [google/evcxr#150]
I can't remember the exact code I used as I only noticed this a while after restarting the evcxr jupyter kernel.

```
thread '<unnamed>' panicked at 'HirDisplay failed when calling Display::fmt!', /home/bjorn/.cargo/registry/src/github.com-1ecc6299db9ec823/ra_ap_hir_ty-0.0.30/src/display.rs:222:17
stack backtrace:
   0: std::panicking::begin_panic
   1: <ra_ap_hir_ty::display::HirDisplayWrapper<T> as core::fmt::Display>::fmt
   2: core::fmt::write
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/fmt/mod.rs:1080
   3: <ra_ap_hir_ty::ProjectionTy as ra_ap_hir_ty::display::HirDisplay>::hir_fmt
   4: <ra_ap_hir_ty::ApplicationTy as ra_ap_hir_ty::display::HirDisplay>::hir_fmt
   5: ra_ap_hir_ty::display::HirDisplay::display_source_code
   6: evcxr::rust_analyzer::RustAnalyzer::top_level_variables
   7: evcxr::eval_context::EvalContext::eval_with_callbacks
   8: evcxr::command_context::CommandContext::execute_with_callbacks
   9: evcxr_jupyter::core::Server::handle_execution_requests
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by davidlattimore** [comment]
Thanks for the report @bjorn3 . It's crashing in code that determines the types of the variables to be persisted. Specifically, in code that writes out those variable types as source code. The line that's crashing in rust-analyzer has a comment that says "This should never happen". It doesn't say why it should never happen though. It's possible there could be some invariant that evcxr is not ensuring in its use of rust-analyzer's APIs.

I update the version of rust-analyzer used by evcxr with each evcxr release and it's possible that whatever the problem was, it could already have been fixed. Hard to tell without a way to reproduce it.

This has got me thinking though, that I should detect the panic and dump a bunch of useful state, including the code currently being executed. That would at least help if this happens in future.
