### ISSUE TITLE
experiencing crashes on recent nightlies

### ISSUE THREAD

**Issue by jonathanstrong** [google/evcxr#176]
```console
$ evcxr
Welcome to evcxr. For help, type :help
>> let mut xs: Vec<u8> = Vec::new();
thread 'main' panicked at 'Internal error, cycle detected:

DatabaseKeyIndex { group_index: 7, query_index: 12, key_index: 372 }
DatabaseKeyIndex { group_index: 7, query_index: 9, key_index: 45 }
', /home/jstrong/.cargo/registry/src/github.com-1ecc6299db9ec823/salsa-0.16.1/src/lib.rs:490:48
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

=============================================================================
Panic detected. Here's some useful information if you're filing a bug report.
<CODE>
let mut xs: Vec<u8> = Vec::new();
</CODE>
<STATE>
ContextState { items_by_name: {}, unnamed_items: [], external_deps: {}, extern_crate_stmts: {}, variable_states: {}, stored_variable_states: {}, async_mode: false, allow_question_mark: false, build_num: 2, config: Config { crate_dir: "redacted", debug_mode: false, preserve_vars_on_panic: false, output_format: "{:?}", display_final_expression: true, expand_use_statements: true, opt_level: "2", error_fmt: ErrorFormat { format_str: "{}", format_trait: "std::fmt::Display" }, time_passes: false, linker: "lld", sccache: None, offline_mode: false, toolchain: "" } }
</STATE>

$ evcxr --version
evcxr 0.9.0

$ rustc --version
rustc 1.54.0-nightly (ca82264ec 2021-05-09)
```

**Comment by thomcc** [comment]
Yep, I've also seen this, haven't tried to debug it though.

**Comment by davidlattimore** [comment]
Thanks for the prompt. CI has been failing for a while due to this and I've been a bit slack investigating. I've managed to reproduce the crash in rust-analyzer and filed a [bug](https://github.com/rust-analyzer/rust-analyzer/issues/8824)

**Comment by Bai-Jinlin** [comment]
me too
`
❯ evcxr
Welcome to evcxr. For help, type :help
>> let a=1;
thread 'main' panicked at 'Internal error, cycle detected:

DatabaseKeyIndex { group_index: 7, query_index: 12, key_index: 372 }
DatabaseKeyIndex { group_index: 7, query_index: 9, key_index: 45 }
', /home/lin/.cargo/registry/src/github.com-1ecc6299db9ec823/salsa-0.16.1/src/lib.rs:490:48
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

=============================================================================
Panic detected. Here's some useful information if you're filing a bug report.
<CODE>
let a=1;
</CODE>
<STATE>
ContextState { items_by_name: {}, unnamed_items: [], external_deps: {}, extern_crate_stmts: {}, variable_states: {}, stored_variable_states: {}, async_mode: false, allow_question_mark: false, build_num: 2, config: Config { crate_dir: "redacted", debug_mode: false, preserve_vars_on_panic: false, output_format: "{:?}", display_final_expression: true, expand_use_statements: true, opt_level: "2", error_fmt: ErrorFormat { format_str: "{}", format_trait: "std::fmt::Display" }, time_passes: false, linker: "lld", sccache: None, offline_mode: false, toolchain: "" } }
</STATE>
`

**Comment by davidlattimore** [comment]
This has recently been fixed in rust analyzer. Unfortunately automatic publishing of rust analyzer to crates.io is currently broken, so that's blocking getting the fix into evcxr... Unless we give up using crates.io as a distribution mechanism

**Comment by ctrlcctrlv** [comment]
Looks like you guys may have figured out the issue, but I've triggered it without even entering a command, just by typing `eprint` and pressing <kbd>Tab</kbd>.

```
[fred@laptop ~]$ RUST_BACKTRACE=full evcxr 
Welcome to evcxr. For help, type :help
>> eprintthread 'main' panicked at 'Internal error, cycle detected:

DatabaseKeyIndex { group_index: 7, query_index: 12, key_index: 372 }
DatabaseKeyIndex { group_index: 7, query_index: 9, key_index: 45 }
', /home/fred/.cargo/registry/src/github.com-1ecc6299db9ec823/salsa-0.16.1/src/lib.rs:490:48
stack backtrace:
   0:     0x55e09cc0d8f0 - std::backtrace_rs::backtrace::libunwind::trace::hdcf4f90f85129e83
                               at /rustc/79e50bf77928f374921a6bcafee3fcff1915f062/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x55e09cc0d8f0 - std::backtrace_rs::backtrace::trace_unsynchronized::h2669e30cb82f6732
                               at /rustc/79e50bf77928f374921a6bcafee3fcff1915f062/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55e09cc0d8f0 - std::sys_common::backtrace::_print_fmt::hfbda19e17f6db318
                               at /rustc/79e50bf77928f374921a6bcafee3fcff1915f062/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x55e09cc0d8f0 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h1a8751bf59281272
                               at /rustc/79e50bf77928f374921a6bcafee3fcff1915f062/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x55e09cc34d0f - core::fmt::write::h7aa6cd0067dca82a
                               at /rustc/79e50bf77928f374921a6bcafee3fcff1915f062/library/core/src/fmt/mod.rs:1094:17
   5:     0x55e09cc09565 - std::io::Write::write_fmt::hd7dd3a1df9b6befb
                               at /rustc/79e50bf77928f374921a6bcafee3fcff1915f062/library/std/src/io/mod.rs:1584:15
   6:     0x55e09cc101fb - std::sys_common::backtrace::_print::h551e9ec8a9fa8106
                               at /rustc/79e50bf77928f374921a6bcafee3fcff1915f062/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x55e09cc101fb - std::sys_common::backtrace::print::ha4b1c5e95fa040b3
                               at /rustc/79e50bf77928f374921a6bcafee3fcff1915f062/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x55e09cc101fb - std::panicking::default_hook::{{closure}}::h0b34c9ab7fb9f857
                               at /rustc/79e50bf77928f374921a6bcafee3fcff1915f062/library/std/src/panicking.rs:208:50
   9:     0x55e09cc0fcdd - std::panicking::default_hook::h3067e8318decd17a
                               at /rustc/79e50bf77928f374921a6bcafee3fcff1915f062/library/std/src/panicking.rs:225:9
  10:     0x55e09cc107ad - std::panicking::rust_panic_with_hook::h81b8facc50f34daa
                               at /rustc/79e50bf77928f374921a6bcafee3fcff1915f062/library/std/src/panicking.rs:591:17
  11:     0x55e09cc103a7 - std::panicking::begin_panic_handler::{{closure}}::ha376ab85d95a000e
                               at /rustc/79e50bf77928f374921a6bcafee3fcff1915f062/library/std/src/panicking.rs:497:13
  12:     0x55e09cc0ddac - std::sys_common::backtrace::__rust_end_short_backtrace::h6795c8afdd1a77e6
                               at /rustc/79e50bf77928f374921a6bcafee3fcff1915f062/library/std/src/sys_common/backtrace.rs:141:18
  13:     0x55e09cc10309 - rust_begin_unwind
                               at /rustc/79e50bf77928f374921a6bcafee3fcff1915f062/library/std/src/panicking.rs:493:5
  14:     0x55e09c3560db - std::panicking::begin_panic_fmt::hf43a0025042538e2
                               at /rustc/79e50bf77928f374921a6bcafee3fcff1915f062/library/std/src/panicking.rs:435:5
  15:     0x55e09c6f881e - salsa::QueryTable<Q>::get::{{closure}}::hf6c2137ebb03a4f3
  16:     0x55e09c8443c4 - <DB as ra_ap_hir_ty::db::HirDatabase>::generic_defaults::__shim::h873262b5cb5d46e3
  17:     0x55e09c7c6f6f - ra_ap_hir_ty::lower::TyLoweringContext::substs_from_path_segment::hd942a69a95b9963b
  18:     0x55e09c7c74a4 - ra_ap_hir_ty::lower::TyLoweringContext::lower_trait_ref_from_path::h4d200ba5232c30ff
  19:     0x55e09c7c7818 - ra_ap_hir_ty::lower::TyLoweringContext::lower_type_bound::hfa2276baaf76496d
  20:     0x55e09c7c7713 - ra_ap_hir_ty::lower::TyLoweringContext::lower_where_predicate::h2c55d0fef05adabc
  21:     0x55e09c7249e1 - <core::iter::adapters::flatten::FlatMap<I,U,F> as core::iter::traits::iterator::Iterator>::next::h11c93094435b62dd
  22:     0x55e09c7376d7 - <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter::h35993481cc05c800
  23:     0x55e09c7c9576 - ra_ap_hir_ty::lower::generic_predicates_for_param_query::h4a94e3349bbbe59b
  24:     0x55e09c8a8381 - salsa::runtime::Runtime::execute_query_implementation::h7b7c56b3d5f61387
  25:     0x55e09c8d5da4 - salsa::derived::slot::Slot<Q,MP>::read_upgrade::hda2d88f552cfb2b8
  26:     0x55e09c8f7769 - salsa::derived::slot::Slot<Q,MP>::read::h51adeb64fa05fc8d
  27:     0x55e09c752828 - <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch::h215df1105c012027
  28:     0x55e09c8441d1 - <DB as ra_ap_hir_ty::db::HirDatabase>::generic_predicates_for_param::__shim::haa7b8703610fb13d
  29:     0x55e09c87ad61 - ra_ap_hir_ty::utils::all_super_trait_refs::h0f8fdc7958a5e480
  30:     0x55e09c87b0e9 - ra_ap_hir_ty::utils::associated_type_by_name_including_super_traits::hf05a62a1bbf943ff
  31:     0x55e09c7c659c - ra_ap_hir_ty::lower::TyLoweringContext::lower_partly_resolved_path::h2e3ae1d842aae49b
  32:     0x55e09c7c5089 - ra_ap_hir_ty::lower::TyLoweringContext::lower_ty_ext::h0e458313169729d5
  33:     0x55e09c7a6bf7 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once::he8ec6bc71a02c323
  34:     0x55e09c723752 - <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::next::h06aa2ec8a46e758e
  35:     0x55e09c73cdac - <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter::h6a13418f1e56f832
  36:     0x55e09c7ca647 - ra_ap_hir_ty::lower::generic_defaults_query::hf3f88e423e6d349e
  37:     0x55e09c8a68a0 - salsa::runtime::Runtime::execute_query_implementation::h161f617d740a3a06
  38:     0x55e09c8c9182 - salsa::derived::slot::Slot<Q,MP>::read_upgrade::h80f5814cff00ffaf
  39:     0x55e09c8f98cd - salsa::derived::slot::Slot<Q,MP>::read::h7205c61f42d15a50
  40:     0x55e09c752d05 - <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch::h27fcda5c6868a190
  41:     0x55e09c844381 - <DB as ra_ap_hir_ty::db::HirDatabase>::generic_defaults::__shim::h873262b5cb5d46e3
  42:     0x55e09c7c6f6f - ra_ap_hir_ty::lower::TyLoweringContext::substs_from_path_segment::hd942a69a95b9963b
  43:     0x55e09c7c74a4 - ra_ap_hir_ty::lower::TyLoweringContext::lower_trait_ref_from_path::h4d200ba5232c30ff
  44:     0x55e09c7cc3e4 - ra_ap_hir_ty::lower::impl_trait_query::hda1f78d0a1dc1896
  45:     0x55e09c8a7d26 - salsa::runtime::Runtime::execute_query_implementation::h71afb6b68a62857c
  46:     0x55e09c8ce82a - salsa::derived::slot::Slot<Q,MP>::read_upgrade::hab7d9ef548ce1ee4
  47:     0x55e09c8f9e3c - salsa::derived::slot::Slot<Q,MP>::read::h95df406255d91e1d
  48:     0x55e09c751cce - <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch::h1270c12cba6255c9
  49:     0x55e09c843f81 - <DB as ra_ap_hir_ty::db::HirDatabase>::impl_trait::__shim::hc699f80c0b204757
  50:     0x55e09c5a3113 - <DB as ra_ap_hir_ty::db::HirDatabase>::impl_trait::ha952cd18a43ee853
  51:     0x55e09c7be1d9 - ra_ap_hir_ty::method_resolution::TraitImpls::trait_impls_in_crate_query::h6f4b18c5e1e31f2b
  52:     0x55e09c8a8bfc - salsa::runtime::Runtime::execute_query_implementation::ha0bbc77383911f93
  53:     0x55e09c8dded9 - salsa::derived::slot::Slot<Q,MP>::read_upgrade::hee03fd59f37ddfec
  54:     0x55e09c8fc8bd - salsa::derived::slot::Slot<Q,MP>::read::hb8b0dbb4a60bc9bf
  55:     0x55e09c75715f - <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch::h9505214ecc4e7ba2
  56:     0x55e09c844486 - <DB as ra_ap_hir_ty::db::HirDatabase>::trait_impls_in_crate::__shim::hce7d571868d1a834
  57:     0x55e09c7be788 - ra_ap_hir_ty::method_resolution::TraitImpls::trait_impls_in_deps_query::h2b2a2918ff637100
  58:     0x55e09c8a76bc - salsa::runtime::Runtime::execute_query_implementation::h61196a90c42de076
  59:     0x55e09c8c6649 - salsa::derived::slot::Slot<Q,MP>::read_upgrade::h6b4d7089ea8c0f18
  60:     0x55e09c8f447d - salsa::derived::slot::Slot<Q,MP>::read::h06259149b9cf6b73
  61:     0x55e09c75228f - <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch::h1edde11c56f1512e
  62:     0x55e09c844506 - <DB as ra_ap_hir_ty::db::HirDatabase>::trait_impls_in_deps::__shim::h1a8ac64b4cbcfa44
  63:     0x55e09c8b0c88 - ra_ap_hir_ty::traits::chalk::<impl chalk_solve::RustIrDatabase<ra_ap_hir_ty::traits::chalk::interner::Interner> for ra_ap_hir_ty::traits::ChalkContext>::impls_for_trait::h310bbcd5625a3215
  64:     0x55e09c869e2a - chalk_recursive::solve::SolveIterationHelpers::solve_from_clauses::hfc72819af9c3c7ae
  65:     0x55e09c861f07 - <chalk_recursive::recursive::Solver<I> as chalk_recursive::solve::SolveDatabase<I>>::solve_goal::h92e60d78e103f33b
  66:     0x55e09c85f9ad - <chalk_recursive::recursive::RecursiveSolver<I> as chalk_solve::solve::Solver<I>>::solve_limited::h3ca5253f9f8282af
  67:     0x55e09c8b381a - ra_ap_hir_ty::traits::trait_solve_query::haf983e8f5f99f548
  68:     0x55e09c8a723a - salsa::runtime::Runtime::execute_query_implementation::h493749becb1e7c0c
  69:     0x55e09c8becef - salsa::derived::slot::Slot<Q,MP>::read_upgrade::h32271eb762da5a83
  70:     0x55e09c8f5d9c - salsa::derived::slot::Slot<Q,MP>::read::h327216d09458da2d
  71:     0x55e09c7565db - <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch::h7a7d33cda9726dd9
  72:     0x55e09c844d52 - <DB as ra_ap_hir_ty::db::HirDatabase>::trait_solve::__shim::h90f4aea16f329d77
  73:     0x55e09c5a31d9 - <DB as ra_ap_hir_ty::db::HirDatabase>::trait_solve::h7e61e2e955bb85fb
  74:     0x55e09c706f93 - ra_ap_hir_ty::autoderef::deref::h747c21c97135222d
  75:     0x55e09c7a4521 - <core::iter::sources::successors::Successors<T,F> as core::iter::traits::iterator::Iterator>::next::hb124511f65466c90
  76:     0x55e09c7ac5a7 - core::iter::traits::iterator::Iterator::find_map::h45217a36a51e8b82
  77:     0x55e09c7d0b4e - ra_ap_hir_ty::infer::expr::<impl ra_ap_hir_ty::infer::InferenceContext>::infer_expr_inner::h8557ce3467a5251d
  78:     0x55e09c7cf098 - ra_ap_hir_ty::infer::expr::<impl ra_ap_hir_ty::infer::InferenceContext>::infer_expr_coerce::hd06a63a4b0770f26
  79:     0x55e09c7d7c52 - ra_ap_hir_ty::infer::expr::<impl ra_ap_hir_ty::infer::InferenceContext>::infer_block::h077aaad59af4aa05
  80:     0x55e09c7d1e90 - ra_ap_hir_ty::infer::expr::<impl ra_ap_hir_ty::infer::InferenceContext>::infer_expr_inner::h8557ce3467a5251d
  81:     0x55e09c7cf098 - ra_ap_hir_ty::infer::expr::<impl ra_ap_hir_ty::infer::InferenceContext>::infer_expr_coerce::hd06a63a4b0770f26
  82:     0x55e09c7dde3a - ra_ap_hir_ty::infer::infer_query::hc420532b9ef015d7
  83:     0x55e09c8a647f - salsa::runtime::Runtime::execute_query_implementation::h0be7c3567bbad5bd
  84:     0x55e09c8c5179 - salsa::derived::slot::Slot<Q,MP>::read_upgrade::h6629e598d1211bf1
  85:     0x55e09c8f926d - salsa::derived::slot::Slot<Q,MP>::read::h6ae396e4ccc5a615
  86:     0x55e09c757984 - <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch::hbcd3794c00a887cb
  87:     0x55e09c843ccf - <DB as ra_ap_hir_ty::db::HirDatabase>::infer_query::__shim::h422146f49bcd9121
  88:     0x55e09c843b3c - ra_ap_hir_ty::db::infer_wait::h7af0f6c0c509a95c
  89:     0x55e09c6dad27 - ra_ap_hir::source_analyzer::SourceAnalyzer::new_for_body::h11d17da609616516
  90:     0x55e09c6b237f - ra_ap_hir::semantics::SemanticsImpl::analyze_impl::h80aa0ddcbcb5f140
  91:     0x55e09c6b0405 - ra_ap_hir::semantics::SemanticsImpl::descend_into_macros::hcb4404de89c80458
  92:     0x55e09c5aa903 - ra_ap_ide_completion::context::CompletionContext::new::hc3d9b728fee11f4c
  93:     0x55e09c5a6737 - ra_ap_ide_completion::completions::h0c370c3a6a1fc949
  94:     0x55e09c5a17b8 - std::panicking::try::h9312a7a10c50ce26
  95:     0x55e09c5a1709 - ra_ap_ide::Analysis::completions::h288e49c64df11df3
  96:     0x55e09c48aa26 - evcxr::rust_analyzer::RustAnalyzer::completions::h23d50f0d396b5e04
  97:     0x55e09c45b6f2 - evcxr::eval_context::EvalContext::completions::hf6780583870a30fb
  98:     0x55e09c42bf6e - evcxr::command_context::CommandContext::completions::h58423b7f3e541359
  99:     0x55e09c3af2d5 - <evcxr_repl::repl::EvcxrRustylineHelper as rustyline::completion::Completer>::complete::h146e368f792573f5
 100:     0x55e09c3a5e2c - rustyline::readline_edit::h58bc68c30a3977d7
 101:     0x55e09c3aab36 - rustyline::Editor<H>::readline::ha6aad611a91e3766
 102:     0x55e09c382ba1 - evcxr::main::h63d52bff2418e052
 103:     0x55e09c386813 - std::sys_common::backtrace::__rust_begin_short_backtrace::ha6486822102d47bd
 104:     0x55e09c386fa9 - std::rt::lang_start::{{closure}}::hff9ee3ab5fd44332
 105:     0x55e09cc10caa - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h3b8c329143d7638a
                               at /rustc/79e50bf77928f374921a6bcafee3fcff1915f062/library/core/src/ops/function.rs:259:13
 106:     0x55e09cc10caa - std::panicking::try::do_call::h4b72c261b4eefc1b
                               at /rustc/79e50bf77928f374921a6bcafee3fcff1915f062/library/std/src/panicking.rs:379:40
 107:     0x55e09cc10caa - std::panicking::try::h703d31b7896cbd49
                               at /rustc/79e50bf77928f374921a6bcafee3fcff1915f062/library/std/src/panicking.rs:343:19
 108:     0x55e09cc10caa - std::panic::catch_unwind::h37cad9b35388a915
                               at /rustc/79e50bf77928f374921a6bcafee3fcff1915f062/library/std/src/panic.rs:431:14
 109:     0x55e09cc10caa - std::rt::lang_start_internal::hab5a8a909af4f90e
                               at /rustc/79e50bf77928f374921a6bcafee3fcff1915f062/library/std/src/rt.rs:34:21
 110:     0x55e09c383472 - main
 111:     0x7fd2d47fcb25 - __libc_start_main
 112:     0x55e09c3574ee - _start
 113:                0x0 - <unknown>
```

**Comment by thomcc** [comment]
Yeah, when I've seen it it often hasn't been with a full command entered.
