### ISSUE TITLE
500 : Internal Server Error - AssertionError: wrong color format 'var(--jp-mirror-editor-variable-color)'

### ISSUE THREAD

**Issue by k-bx** [google/evcxr#187]
After installing on Ubuntu 20.04 per README, getting this error upon creating a new notebook: 500 : Internal Server Error

Terminal log looks like this:

```
kb at z2 in ~/workspace/adinmo/notebooks (master●)  ⌚ 16:24:50
$ jupyter-notebook
[I 16:24:52.273 NotebookApp] Serving notebooks from local directory: /home/kb/workspace/adinmo/notebooks
[I 16:24:52.273 NotebookApp] Jupyter Notebook 6.2.0 is running at:
[I 16:24:52.273 NotebookApp] http://localhost:8888/?token=e7ed8b9d4b029560a56598ed9490a124e5591852add7b59f
[I 16:24:52.273 NotebookApp]  or http://127.0.0.1:8888/?token=e7ed8b9d4b029560a56598ed9490a124e5591852add7b59f
[I 16:24:52.273 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 16:24:52.317 NotebookApp]

    To access the notebook, open this file in a browser:
        file:///home/kb/.local/share/jupyter/runtime/nbserver-1272437-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/?token=e7ed8b9d4b029560a56598ed9490a124e5591852add7b59f
     or http://127.0.0.1:8888/?token=e7ed8b9d4b029560a56598ed9490a124e5591852add7b59f
[I 16:25:02.464 NotebookApp] Creating new notebook in
[E 16:25:02.581 NotebookApp] Uncaught exception GET /notebooks/Untitled.ipynb?kernel_name=rust (127.0.0.1)
    HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/notebooks/Untitled.ipynb?kernel_name=rust', version='HTTP/1.1', remote_ip='127.0.0.1')
    Traceback (most recent call last):
      File "/home/kb/.local/lib/python3.8/site-packages/tornado/web.py", line 1704, in _execute
        result = await result
      File "/home/kb/.local/lib/python3.8/site-packages/tornado/gen.py", line 775, in run
        yielded = self.gen.send(value)
      File "/home/kb/.local/lib/python3.8/site-packages/notebook/notebook/handlers.py", line 95, in get
        self.write(self.render_template('notebook.html',
      File "/home/kb/.local/lib/python3.8/site-packages/notebook/base/handlers.py", line 516, in render_template
        return template.render(**ns)
      File "/home/kb/.local/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
        self.environment.handle_exception()
      File "/home/kb/.local/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
        reraise(*rewrite_traceback_stack(source=source))
      File "/home/kb/.local/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
        raise value.with_traceback(tb)
      File "/home/kb/.local/lib/python3.8/site-packages/notebook/templates/notebook.html", line 1, in top-level template code
        {% extends "page.html" %}
      File "/home/kb/.local/lib/python3.8/site-packages/notebook/templates/page.html", line 154, in top-level template code
        {% block header %}
      File "/home/kb/.local/lib/python3.8/site-packages/notebook/templates/notebook.html", line 115, in block "header"
        {% for exporter in get_frontend_exporters() %}
      File "/home/kb/.local/lib/python3.8/site-packages/notebook/notebook/handlers.py", line 23, in get_frontend_exporters
        from nbconvert.exporters.base import get_export_names, get_exporter
      File "/home/kb/.local/lib/python3.8/site-packages/nbconvert/__init__.py", line 4, in <module>
        from .exporters import *
      File "/home/kb/.local/lib/python3.8/site-packages/nbconvert/exporters/__init__.py", line 4, in <module>
        from .slides import SlidesExporter
      File "/home/kb/.local/lib/python3.8/site-packages/nbconvert/exporters/slides.py", line 12, in <module>
        from ..preprocessors.base import Preprocessor
      File "/home/kb/.local/lib/python3.8/site-packages/nbconvert/preprocessors/__init__.py", line 7, in <module>
        from .csshtmlheader import CSSHTMLHeaderPreprocessor
      File "/home/kb/.local/lib/python3.8/site-packages/nbconvert/preprocessors/csshtmlheader.py", line 14, in <module>
        from jupyterlab_pygments import JupyterStyle
      File "/home/kb/.local/lib/python3.8/site-packages/jupyterlab_pygments/__init__.py", line 4, in <module>
        from .style import JupyterStyle
      File "/home/kb/.local/lib/python3.8/site-packages/jupyterlab_pygments/style.py", line 10, in <module>
        class JupyterStyle(Style):
      File "/usr/lib/python3/dist-packages/pygments/style.py", line 101, in __new__
        ndef[0] = colorformat(styledef)
      File "/usr/lib/python3/dist-packages/pygments/style.py", line 58, in colorformat
        assert False, "wrong color format %r" % text
    AssertionError: wrong color format 'var(--jp-mirror-editor-variable-color)'
[E 16:25:02.589 NotebookApp] {
      "Host": "localhost:8888",
      "Connection": "keep-alive",
      "Sec-Ch-Ua": "\" Not;A Brand\";v=\"99\", \"Google Chrome\";v=\"91\", \"Chromium\";v=\"91\"",
      "Sec-Ch-Ua-Mobile": "?0",
      "Upgrade-Insecure-Requests": "1",
      "User-Agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36",
      "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
      "Sec-Fetch-Site": "same-origin",
      "Sec-Fetch-Mode": "navigate",
      "Sec-Fetch-Dest": "document",
      "Referer": "http://localhost:8888/tree",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "uk-UA,uk;q=0.9,en-US;q=0.8,en;q=0.7,fr-FR;q=0.6,fr;q=0.5,ru;q=0.4",
      "Cookie": "ajs_user_id=%2241310ae8-b828-5fe8-8493-db1e8736dec5%22; ajs_anonymous_id=%22c56a26ef-50ad-44fd-a7e5-fd334cf4b6ef%22; _hp2_ses_props.1823968819=%7B%22ts%22%3A1626094507494%2C%22d%22%3A%22localhost%22%2C%22h%22%3A%22%2F%22%7D; _hp2_id.1823968819=%7B%22userId%22%3A%221260604555634903%22%2C%22pageviewId%22%3A%221469411284624775%22%2C%22sessionId%22%3A%226072587294056250%22%2C%22identity%22%3A%2241310ae8-b828-5fe8-8493-db1e8736dec5%22%2C%22trackerVersion%22%3A%224.0%22%2C%22identityField%22%3Anull%2C%22isIdentified%22%3A1%2C%22oldIdentity%22%3Anull%7D; _xsrf=2|3a29c372|74603acd2b305d0c26c5fb736a6b0f8d|1626096175; username-localhost-8888=\"2|1:0|10:1626096293|23:username-localhost-8888|44:Yzc0NTBmM2ZkNDZjNGEzYThiZWMwMjNlOTE0MmVlMGE=|7a39dbd0860f04f865ca5be2cb04df0375ff9090bd9cb3b6003ed294c3a3cadb\""
    }
[E 16:25:02.589 NotebookApp] 500 GET /notebooks/Untitled.ipynb?kernel_name=rust (127.0.0.1) 81.500000ms referer=http://localhost:8888/tree
[E 16:25:07.872 NotebookApp] Uncaught exception GET /notebooks/Untitled.ipynb?kernel_name=rust (127.0.0.1)
    HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/notebooks/Untitled.ipynb?kernel_name=rust', version='HTTP/1.1', remote_ip='127.0.0.1')
    Traceback (most recent call last):
      File "/home/kb/.local/lib/python3.8/site-packages/tornado/web.py", line 1704, in _execute
        result = await result
      File "/home/kb/.local/lib/python3.8/site-packages/tornado/gen.py", line 775, in run
        yielded = self.gen.send(value)
      File "/home/kb/.local/lib/python3.8/site-packages/notebook/notebook/handlers.py", line 95, in get
        self.write(self.render_template('notebook.html',
      File "/home/kb/.local/lib/python3.8/site-packages/notebook/base/handlers.py", line 516, in render_template
        return template.render(**ns)
      File "/home/kb/.local/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
        self.environment.handle_exception()
      File "/home/kb/.local/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
        reraise(*rewrite_traceback_stack(source=source))
      File "/home/kb/.local/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
        raise value.with_traceback(tb)
      File "/home/kb/.local/lib/python3.8/site-packages/notebook/templates/notebook.html", line 1, in top-level template code
        {% extends "page.html" %}
      File "/home/kb/.local/lib/python3.8/site-packages/notebook/templates/page.html", line 154, in top-level template code
        {% block header %}
      File "/home/kb/.local/lib/python3.8/site-packages/notebook/templates/notebook.html", line 115, in block "header"
        {% for exporter in get_frontend_exporters() %}
      File "/home/kb/.local/lib/python3.8/site-packages/notebook/notebook/handlers.py", line 40, in get_frontend_exporters
        for name in get_export_names():
      File "/home/kb/.local/lib/python3.8/site-packages/nbconvert/exporters/base.py", line 141, in get_export_names
        e = get_exporter(exporter_name)(config=config)
      File "/home/kb/.local/lib/python3.8/site-packages/nbconvert/exporters/base.py", line 101, in get_exporter
        exporter = entrypoints.get_single('nbconvert.exporters', name).load()
      File "/usr/lib/python3/dist-packages/entrypoints.py", line 79, in load
        mod = import_module(self.module_name)
      File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
      File "<frozen importlib._bootstrap>", line 991, in _find_and_load
      File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
      File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
      File "<frozen importlib._bootstrap>", line 991, in _find_and_load
      File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
      File "<frozen importlib._bootstrap_external>", line 848, in exec_module
      File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
      File "/home/kb/.local/lib/python3.8/site-packages/nbconvert/__init__.py", line 6, in <module>
        from . import preprocessors
      File "/home/kb/.local/lib/python3.8/site-packages/nbconvert/preprocessors/__init__.py", line 7, in <module>
        from .csshtmlheader import CSSHTMLHeaderPreprocessor
      File "/home/kb/.local/lib/python3.8/site-packages/nbconvert/preprocessors/csshtmlheader.py", line 14, in <module>
        from jupyterlab_pygments import JupyterStyle
      File "/home/kb/.local/lib/python3.8/site-packages/jupyterlab_pygments/__init__.py", line 4, in <module>
        from .style import JupyterStyle
      File "/home/kb/.local/lib/python3.8/site-packages/jupyterlab_pygments/style.py", line 10, in <module>
        class JupyterStyle(Style):
      File "/usr/lib/python3/dist-packages/pygments/style.py", line 101, in __new__
        ndef[0] = colorformat(styledef)
      File "/usr/lib/python3/dist-packages/pygments/style.py", line 58, in colorformat
        assert False, "wrong color format %r" % text
    AssertionError: wrong color format 'var(--jp-mirror-editor-variable-color)'
[E 16:25:07.874 NotebookApp] {
      "Host": "localhost:8888",
      "Connection": "keep-alive",
      "Cache-Control": "max-age=0",
      "Sec-Ch-Ua": "\" Not;A Brand\";v=\"99\", \"Google Chrome\";v=\"91\", \"Chromium\";v=\"91\"",
      "Sec-Ch-Ua-Mobile": "?0",
      "Upgrade-Insecure-Requests": "1",
      "User-Agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36",
      "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
      "Sec-Fetch-Site": "same-origin",
      "Sec-Fetch-Mode": "navigate",
      "Sec-Fetch-User": "?1",
      "Sec-Fetch-Dest": "document",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "uk-UA,uk;q=0.9,en-US;q=0.8,en;q=0.7,fr-FR;q=0.6,fr;q=0.5,ru;q=0.4",
      "Cookie": "ajs_user_id=%2241310ae8-b828-5fe8-8493-db1e8736dec5%22; ajs_anonymous_id=%22c56a26ef-50ad-44fd-a7e5-fd334cf4b6ef%22; _hp2_ses_props.1823968819=%7B%22ts%22%3A1626094507494%2C%22d%22%3A%22localhost%22%2C%22h%22%3A%22%2F%22%7D; _hp2_id.1823968819=%7B%22userId%22%3A%221260604555634903%22%2C%22pageviewId%22%3A%221469411284624775%22%2C%22sessionId%22%3A%226072587294056250%22%2C%22identity%22%3A%2241310ae8-b828-5fe8-8493-db1e8736dec5%22%2C%22trackerVersion%22%3A%224.0%22%2C%22identityField%22%3Anull%2C%22isIdentified%22%3A1%2C%22oldIdentity%22%3Anull%7D; _xsrf=2|3a29c372|74603acd2b305d0c26c5fb736a6b0f8d|1626096175; username-localhost-8888=\"2|1:0|10:1626096293|23:username-localhost-8888|44:Yzc0NTBmM2ZkNDZjNGEzYThiZWMwMjNlOTE0MmVlMGE=|7a39dbd0860f04f865ca5be2cb04df0375ff9090bd9cb3b6003ed294c3a3cadb\""
    }
[E 16:25:07.874 NotebookApp] 500 GET /notebooks/Untitled.ipynb?kernel_name=rust (127.0.0.1) 144.630000ms referer=None

```

**Comment by k-bx** [comment]
Reinstalling via `pip` and then doing `pip3 install -U pygments` helped.
