### ISSUE TITLE
`File` causes segfaults (evcxr_repl)

### ISSUE THREAD

**Issue by LoganDark** [google/evcxr#226]
It looks like on my machine, trying to use a `File` declared on a different line results in a segfault:

```
logandark@LoganDark-ASUS:~/CLionProjects/whatever$ evcxr
Welcome to evcxr. For help, type :help
>> let mut file = std::fs::File::open("whatever.bin").unwrap();
>> std::io::Write::write_all(&mut file, b"Hello, World!\n").unwrap();
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 9, kind: Uncategorized, message: "Bad file descriptor" }', src/lib.rs:111:57
stack backtrace:
   0: rust_begin_unwind
             at /rustc/28b891916d4c85cd10fb2e9cfa8bc836a2c459f3/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/28b891916d4c85cd10fb2e9cfa8bc836a2c459f3/library/core/src/panicking.rs:142:14
   2: core::result::unwrap_failed
             at /rustc/28b891916d4c85cd10fb2e9cfa8bc836a2c459f3/library/core/src/result.rs:1805:5
   3: run_user_code_11
   4: evcxr::runtime::Runtime::run_loop
   5: evcxr::runtime::runtime_hook
   6: evcxr::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Segmentation fault.
   0: evcxr::runtime::Runtime::install_crash_handlers::segfault_handler
   1: <unknown>
   2: _mi_free_block_mt
   3: alloc::alloc::dealloc
             at /rustc/28b891916d4c85cd10fb2e9cfa8bc836a2c459f3/library/alloc/src/alloc.rs:107:14
      <alloc::alloc::Global as core::alloc::Allocator>::deallocate
             at /rustc/28b891916d4c85cd10fb2e9cfa8bc836a2c459f3/library/alloc/src/alloc.rs:244:22
      alloc::alloc::box_free
             at /rustc/28b891916d4c85cd10fb2e9cfa8bc836a2c459f3/library/alloc/src/alloc.rs:342:9
      panic_unwind::real_imp::cleanup
             at /rustc/28b891916d4c85cd10fb2e9cfa8bc836a2c459f3/library/panic_unwind/src/gcc.rs:83:5
      __rust_panic_cleanup
             at /rustc/28b891916d4c85cd10fb2e9cfa8bc836a2c459f3/library/panic_unwind/src/lib.rs:101:19
   4: std::panicking::try::cleanup
             at /rustc/28b891916d4c85cd10fb2e9cfa8bc836a2c459f3/library/std/src/panicking.rs:473:42
      std::panicking::try::do_catch
             at /rustc/28b891916d4c85cd10fb2e9cfa8bc836a2c459f3/library/std/src/panicking.rs:517:23
      std::panicking::try
             at /rustc/28b891916d4c85cd10fb2e9cfa8bc836a2c459f3/library/std/src/panicking.rs:456:19
      std::panic::catch_unwind
             at /rustc/28b891916d4c85cd10fb2e9cfa8bc836a2c459f3/library/std/src/panic.rs:137:14
      std::rt::lang_start_internal::{{closure}}
             at /rustc/28b891916d4c85cd10fb2e9cfa8bc836a2c459f3/library/std/src/rt.rs:128:48
      std::panicking::try::do_call
             at /rustc/28b891916d4c85cd10fb2e9cfa8bc836a2c459f3/library/std/src/panicking.rs:492:40
      std::panicking::try
             at /rustc/28b891916d4c85cd10fb2e9cfa8bc836a2c459f3/library/std/src/panicking.rs:456:19
      std::panic::catch_unwind
             at /rustc/28b891916d4c85cd10fb2e9cfa8bc836a2c459f3/library/std/src/panic.rs:137:14
      std::rt::lang_start_internal
             at /rustc/28b891916d4c85cd10fb2e9cfa8bc836a2c459f3/library/std/src/rt.rs:128:20
   5: main
   6: __libc_start_main
   7: _start

Child process terminated with status: signal: 6
>> 
```

Apparently every line is run in its own subprocess, and variables are just conjured up by magic? At least that's what I'm gathering from whatever is going on here. The REPL didn't crash, I could actually try again - and this worked without segfaulting:

```
>> std::io::Write::write_all(&mut std::fs::File::open("whatever.bin").unwrap(), b"Hello, World!\n").unwrap();
```

However, when I tried to reproduce this, it looks like `File` *sometimes* works, and also other variables *sometimes* decide to disappear. I'm really not sure how this works - is evcxr using some kind of heuristic to figure out what it should do?

In any case, segfaults are bad!

**Comment by davidlattimore** [comment]
Interesting. I'd never thought to try that.

So each line is actually being run in the same subprocess. Each line gets compiled into a shared object (.so on Linux, .dylib on Mac or .dll on Windows).

If you run `evcxr`, then in a separate shell, determine what process ID the `evcxr` subprocess has:

```
# ps gx | grep '[b]in/evcxr'
103171 pts/1    S<+    0:00 /home/user/.cargo/bin/evcxr
```

You can then poke around in /proc to see what's happening:

```
# cd /proc/103171/fd
# ls -l
total 0
lr-x------ 1 user user 64 Jun 12 14:17 0 -> 'pipe:[419049]'
l-wx------ 1 user user 64 Jun 12 14:17 1 -> 'pipe:[419050]'
l-wx------ 1 user user 64 Jun 12 14:17 2 -> 'pipe:[419051]'
lr-x------ 1 user user 64 Jun 12 14:17 3 -> /home/user/tmp/whatever.txt
```

So the file is still open - at least until the panic occurs, then it gets closed.

I thought perhaps something in libc or the Rust libraries was keeping track of which files it had open and ending up with multiple separate tables somehow. However by running the subprocess under strace, I found that this wasn't the case - the system calls reported by strace seem to be as expected:

```
openat(AT_FDCWD, "/home/user/tmp/whatever.txt", O_RDONLY|O_CLOEXEC) = 3
....
write(3, "Hello, World!\n", 14)         = -1 EBADF (Bad file descriptor)
```

As far as I can tell, this seems to be the behavior of ldopen on Linux. I was able to reproduce the same problem with a C program loading a couple of shared objects compiled from C. I wasn't able to find this behavior documented anywhere. Here's the C code I used to reproduce this in C: [c-dlopen.tar.gz](https://github.com/google/evcxr/files/8885329/c-dlopen.tar.gz)

**Comment by LoganDark** [comment]
> Interesting. I'd never thought to try that.

I'm using evcxr to write out lookup tables so I don't have to generate them in a build script (it can get [pretty](https://github.com/LoganDark/rgb565/blob/8c4c87150bdce2395a76060fe56f745c3fc46420/src/lut.rs) [involved](https://github.com/LoganDark/rgb565/blob/8c4c87150bdce2395a76060fe56f745c3fc46420/build.rs#L35-L49)), and can just `include_bytes!` them directly. It's the easiest to just do the thing locally and then just distribute the files with the crate. I used to use Python for general REPL things, but I don't like Python anymore :P.

Opening the file in the same line seems to always have the intended behavior. Then as a temporary it also gets dropped in a timely fashion to prevent a later segfault.

Is this an issue that can be fixed by evcxr or is it just a Linux limitation of some sort?

**Comment by davidlattimore** [comment]
Opps, seems I completely misinterpreted what was happening.

I just discovered that the Bad file descriptor error is actually because the file wasn't opened for writing, only for reading.

The following works:

```
>> let mut file = std::fs::File::create("file2.txt").unwrap();
>> std::io::Write::write_all(&mut file, b"Hello, World!\n").unwrap();
```

Apparently I haven't used the C `open`function in too long - I forgot to pass the `O_WRONLY` flag and ended up reproducing the same bug in the C code as was in the original Rust code.

**Comment by LoganDark** [comment]
Oops - I accidentally used open instead of create. I guess that's my issue.

Should I close this?

**Comment by bjorn3** [comment]
Evcxr shouldn't segfault when unwrapping an error result, so I think this issue should be kept open.

**Comment by LoganDark** [comment]
> Evcxr shouldn't segfault when unwrapping an error result, so I think this issue should be kept open.

AFAIK, it doesn't, it invokes undefined behavior by somehow corrupting the File / making it invalid, causing its Drop impl to segfault

**Comment by bjorn3** [comment]
I think I found the issue. The main function of the executed snippet (`run_user_code_???`) is declared with the `extern "C"` abi. Unwinding through this is UB. Evcxr will need to add a `std::panic::catch_unwind` wrapper to catch panics.

**Comment by LoganDark** [comment]
> I think I found the issue. The main function of the executed snippet (`run_user_code_???`) is declared with the `extern "C"` abi. Unwinding through this is UB. Evcxr will need to add a `std::panic::catch_unwind` wrapper to catch panics.

This is interesting. Has evcxr been audited for undefined behavior, or is it just on a best-effort basis?

**Comment by davidlattimore** [comment]
Setting the option `:preserve_vars_on_panic 1` will wrap the user code in a catch_unwind and does prevent the segfault. Possibly I should revisit at least the default for that option. We used to always have a catch_unwind block, but I removed it by default because I found that was increasing compilation time more than I would have liked. That was some time ago that that was the case, so it's possible that it no longer affects compilation time in that way.

**Comment by davidlattimore** [comment]
I was hopeful I might find a way to make it not panic without adding in a `catch_unwind`. I figured that setting `panic = "abort"` in Cargo.toml would do. Unfortunately that option doesn't work since we're compiling with `-C prefer-dynamic`.

```
error: the linked panic runtime `panic_unwind` is not compiled with this crate's panic strategy `abort`
```

So I'll just change the default for now... looks like I only made the question mark operator work when not catching panics, so I need to fix that before I change the default.
