### ISSUE TITLE
Segfault on unwraping an option

### ISSUE THREAD

**Issue by HKalbasi** [google/evcxr#237]
```
Welcome to evcxr. For help, type :help
>> let x: Option<i32> = None;
>> x.unwrap()
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', src/lib.rs:123:3
stack backtrace:
   0: rust_begin_unwind
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/panicking.rs:142:14
   2: core::panicking::panic
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/panicking.rs:48:5
   3: run_user_code_3
   4: evcxr::runtime::Runtime::run_loop
   5: evcxr::runtime::runtime_hook
   6: evcxr::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Segmentation fault.
   0: evcxr::runtime::Runtime::install_crash_handlers::segfault_handler
   1: <unknown>
   2: mi_free
   3: alloc::alloc::dealloc
             at /rustc/ddcbba036aee08f0709f98a92a342a278eae5c05/library/alloc/src/alloc.rs:107:14
      <alloc::alloc::Global as core::alloc::Allocator>::deallocate
             at /rustc/ddcbba036aee08f0709f98a92a342a278eae5c05/library/alloc/src/alloc.rs:244:22
      alloc::alloc::box_free
             at /rustc/ddcbba036aee08f0709f98a92a342a278eae5c05/library/alloc/src/alloc.rs:342:9
      panic_unwind::real_imp::cleanup
             at /rustc/ddcbba036aee08f0709f98a92a342a278eae5c05/library/panic_unwind/src/gcc.rs:83:5
      __rust_panic_cleanup
             at /rustc/ddcbba036aee08f0709f98a92a342a278eae5c05/library/panic_unwind/src/lib.rs:100:19
   4: std::panicking::try::cleanup
             at /rustc/ddcbba036aee08f0709f98a92a342a278eae5c05/library/std/src/panicking.rs:473:42
      std::panicking::try::do_catch
             at /rustc/ddcbba036aee08f0709f98a92a342a278eae5c05/library/std/src/panicking.rs:517:23
      std::panicking::try
             at /rustc/ddcbba036aee08f0709f98a92a342a278eae5c05/library/std/src/panicking.rs:456:19
      std::panic::catch_unwind
             at /rustc/ddcbba036aee08f0709f98a92a342a278eae5c05/library/std/src/panic.rs:137:14
      std::rt::lang_start_internal::{{closure}}
             at /rustc/ddcbba036aee08f0709f98a92a342a278eae5c05/library/std/src/rt.rs:128:48
      std::panicking::try::do_call
             at /rustc/ddcbba036aee08f0709f98a92a342a278eae5c05/library/std/src/panicking.rs:492:40
      std::panicking::try
             at /rustc/ddcbba036aee08f0709f98a92a342a278eae5c05/library/std/src/panicking.rs:456:19
      std::panic::catch_unwind
             at /rustc/ddcbba036aee08f0709f98a92a342a278eae5c05/library/std/src/panic.rs:137:14
      std::rt::lang_start_internal
             at /rustc/ddcbba036aee08f0709f98a92a342a278eae5c05/library/std/src/rt.rs:128:20
   5: main
   6: __libc_start_call_main
             at ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
   7: __libc_start_main_impl
             at ./csu/../csu/libc-start.c:392:3
   8: _start

Subprocess terminated with status: signal: 6 (SIGABRT) (core dumped)
```
In jupyter notebook it will cause losing defined variables.

I guess it is because evcxr will try to print the variable, but there is nothing valid there after panic. I searched segmentation fault and found nothing relevant, but sorry if it is duplicate.

**Comment by bjorn3** [comment]
See https://github.com/google/evcxr/issues/226#issuecomment-1153222248

> In jupyter notebook it will cause losing defined variables.

If you want to preserve variables after panics you need to use `:preserve_vars_on_panic 1`, which should also fix the segfault by wrapping the code in catch_unwind.

**Comment by HKalbasi** [comment]
Thank you

Personally I think `catch_unwind` should be the default, unless it significantly make things slower (and even then we should probably investigate why it is and solve it)

And #226 is enough for tracking this, so closing.
